bokysan/docker-postfix

- postfix.sh
Relayhost is set from the MYNETWORKS environment variable instead of the mynetworks variable.  
Could I also suggest explicitly adding a license to this repo?
> Fixed issue where relayhost was set instead of mynetworks.

- Dockerfile
- README.md
- header_checks
- run.sh
I added the HEADER_CHECKS [1] option with a sample configuration.
Each message header line is compared against a pre-configured list of patterns. When a match is found the corresponding action is executed.
I have tested this version of the docker image in a flask application and checked if the headers where ignored or replaced.
[1]: http://www.postfix.org/header_checks.5.html
> Added HEADER_CHECKS configuration option

- Dockerfile
- README.md
- run.sh
This PR allows setting an empty `ALLOWED_SENDER_DOMAINS` variable. The default behaviour remains the same (empty `ALLOWED_SENDER_DOMAINS` will throw an error), but it is posible to override this behaviour via a new variable `ALLOW_EMPTY_SENDER_DOMAINS`.
The use case is being able to set restrictions on the recipient and not on the sender (anyone can send mails but just to a single domain for instance). This can be achieved by extending the image through custom scripts, and it's cleaner if the base image supports a way not to enforce setting a value on it.
> Allow setting empty ALLOWED_SENDER_DOMAINS

- Dockerfile
- commons.sh
- run.sh
This PR splits the `run.sh` bootstrap script into two different scripts: `common.sh` and `run.sh`. `commons.sh` will contain common logic and functions and `run.sh` will contain`postfix`  logic and will source `commons.sh`.
The use case is being able to reuse the common methods when extending the image so that the behaviour is consistent (e.g: same formatting for log messages) without needing to repeat the code while extending.
> Decouple commons.sh from run.sh

- Dockerfile
- push.sh
Fixes: #19 
Here's a proposal to consider for:
- supporting multiple alpine base image versions
- a script that handles building/tagging/pushing images to docker hub
I tested this out using my own docker hub username, and this seems to work as expected: https://hub.docker.com/repository/docker/mattcritchlow/postfix
This was done running the command: `./push.sh latest 3.10 3.9`
I'm not sure if this completely meets your needs, but hopefully it's a start.
> Support alpine versions

- .gitignore
- Dockerfile
- README.md
- integration-tests.sh
- integration-tests/xoauth2-error/docker-compose.yml
- integration-tests/xoauth2-error/it/test.bats
- integration-tests/xoauth2/common/common-xoauth2.sh
- integration-tests/xoauth2/docker-compose.yml
- integration-tests/xoauth2/it/test.bats
- scripts/common-run.sh
- scripts/common.sh
- scripts/run.sh
- unit-tests/Dockerfile
- unit-tests/xoauth2_support.bats
This PR, uses https://github.com/tarickb/sasl-xoauth2 to add support for the XOAuth2 authentication method that is usually required / recommend for some providers like GMail. Currently this library it is specifically designed for GMail, but seems that there is a discussion to provide support for [other providers like Office365](https://github.com/tarickb/sasl-xoauth2/issues/4) ([there is an active PR](https://github.com/tarickb/sasl-xoauth2/pull/5)).
More precisely, this PR does:
- Changes the Dockerfile to add a multi-stage build to build the SASL XOAuth2 library and then copy the result to the actual image. This build stage is configurable using docker build args.
- Define and document `RELAYHOST_TLS_LEVEL`, `XOAUTH2_CLIENT_ID`, `XOAUTH2_SECRET`, `XOAUTH2_INITIAL_ACCESS_TOKEN`, …
> Add XOAuth2 support for GMail

- README.md
- helm/mail/templates/statefulset.yaml
- helm/mail/values.yaml
> add persistence.existingClaim

- README.md
- helm/mail/templates/service.yaml
- helm/mail/values.yaml
This PR allows to specify a value for `nodePort` if `service.type` is `NodePort`. If the value is not set it will allocate a random port (so won't change the previous behaviour).
> Add option to use a specific nodePort

- README.md
- helm/mail/values.yaml
- scripts/common-run.sh
This PR adds a `SASL_RELAYHOST` variable that overwrites the `RELAYHOST` inside the `sasl_passwd` file when specified (see #76).
By default, the `RELAYHOST` value will be used, as is currently the case.
Let me know if you have any questions or concerns.
Thanks a lot!
> add SASL_RELAYHOST to overwrite RELATHOST in sasl_passwd file on demand

- README.md
Reading the documentation I found a mismatch between README and code about the `POSTFIX_myhostname` envar.
> Fix: README `POSTFIX_myhostname` envar name

- README.md
- helm/mail/templates/statefulset.yaml
- helm/mail/values.yaml
- helm/test_11_existing_secret.yml
Hi this PR seeks to implement functionality to load existing secrets as environment variables in the pod.
The rationale behind this PR:
We use a controller that retrieves secrets from an external system and creates them in kubernetes. This PR would allow us to deploy this helmchart which simply consumes the existing secret provisioned by the controller.
> Add feature to bring your own secret resource

- helm/mail/templates/configmap.yaml
STARTTLS command is not implemented because TLS is enabled on the outgoing instead of the incoming traffic. smtp in smtp_use_tls needs to be replaced by smtpd
> fix: STARTTLS command not implemented

- README.md
- scripts/common-run.sh
In case of Microsoft 365 smartrelay : 
$XOAUTH2_CLIENT_ID" can't be mandatory.
$XOAUTH2_TOKEN_ENDPOINT parameter added.
If the application will be restricted to one tenant the token edpoint is neened
> For Microsoft 365 use ,

- .github/workflows/tags.yml
Fixing the issue when container will not restart due to duplicate sasl auth configuration  file entries.
> fix: do not duplicate sasl configuration entries on restart

- .github/workflows/tags.yml
As noted in https://helm.sh/docs/topics/charts/#the-chartyaml-file, a helm chart's version must be semver 2.0.0.
Since semver 2.0.0 strictly prescribes the "{major}.{minor}.{patch}" format, the shell string interpolation is used to remove the `v` prefix.
> fix: helm version must be semver

- build-scripts/postfix-install.sh
Kubernetes `startupProbe` uses `ps` to check if components are running.
`ps` is not present in the image, triggering a pod restart loop.
> Install procps on debian

- helm/mail/templates/service-monitor.yaml
The selector for the ServiceMonitor currently will not match the underlying service:
```yaml
selector:
matchLabels:
app.kubernetes.io/instance: {{ $chart }}
prometheus: unknown
```
1. `app.kubernetes.io/instance: {{ $chart }}` will only work if the release is named `mail`, because `$chart` is hard-coded to that value here. But that's not always the case.
1. `prometheus: unknown` will cause this to never match because this label isn't applied to the underlying service (unless it is explicitly set in the values provided the helm chart). 
Fixes #162
> Fix ServiceMonitor selector

- Dockerfile
avoids error message `improper command pipelining after CONNECT from unknown[172.20.0.1]: EHLO healthcheck\n` in postfix logs by proper command sequencing and closes the `nc` connection properly.
> improved healthcheck with proper command sequence

- scripts/common-run.sh
We encountered an issue where the script common-run.sh would fail if the SMTPD_SASL_USERS environment variable was defined. The failure occurred immediately after displaying the "Enable smtpd sasl auth" message, preventing the container from starting correctly.
The root cause was traced to a conditional check for the existence of the /etc/sasl2/sasldb2 file. When the file did not exist, the subsequent `chown` operation was skipped as intended, but the script would still fail due to an undefined behavior in the shell context.
The addition of a debug message "Sasldb configured" before the closing `fi` statement has resolved the issue. This change appears to stabilize the script execution, allowing the container to start as expected.
While the underlying cause is not fully understood and …
> Fix sasldb with SMTPD_SASL_USERS  env variable

- helm/mail/templates/statefulset.yaml
Use the full volumeClaimTemplates spec to avoid manifest diffs when using ServerSideApply/Diff.
Example:
> Expand volumeClaimTemplates spec

- helm/mail/templates/hpa.yaml
- helm/mail/values.yaml
apiVersion: "autoscaling/v2beta1" is deprecated, adding value for overriding api version, fore example apiVersion: autoscaling/v2
> autoscaling.apiVersion

- helm/mail/templates/service.yaml
Hey, ive encountered strange behavior inside and ipv6 eks cluster and traced it to set the right protocol when using (mandatory) (m)tls.
if you do not do this, the ingress will wait for your first input and the welcome header wont get transmitted to the sender. didnt open an issue as this fix was pretty obvious
> Add missing appProtocol

- README.md
I ran into an issue when testing because _I missed_ that the generated SES SMTP credentials that are region specific.  I generated credentials in our production region but was testing in one of our DR regions.  This may help others avoid this issue in the future and not bother @bokysan .. :)
> Mention SES Creds are Region Specific, fix broken URL

- README.md
This is a typo, the field is named `container.postfix.securityContext`
@bokysan on a related topic, would you accept a PR to support a security context for the exporter container?
> Fix `container.postfixsecurityContext`

- scripts/common-run.sh
- scripts/run.sh
Fixes https://github.com/bokysan/docker-postfix/issues/212. This appears to be a common strategy: https://github.com/docker-mailserver/docker-mailserver/blob/c29fe3ff0bc888016720536228878b3f19131056/Dockerfile#L259.
```shell
root@postfix-mail-0:/tmp# /etc/cron.daily/logrotate
error: rsyslog:1 duplicate log entry for /var/log/mail.log
error: found error in file rsyslog, skipping
root@postfix-mail-0:/tmp# echo $?
1
root@postfix-mail-0:/tmp# cat /etc/logrotate.d/logrotate.conf
/var/log/mail.log {
copytruncate
rotate 1
monthly
minsize 1M
compress
missingok
notifempty
dateext
olddir /var/log/
maxage 90
}
```
```
root@postfix-mail-0:/tmp# if egrep -q '^/var/log/mail.log' /etc/logrotate.d/logrotate.conf; then
echo "Removing /var/log/mail.log from /etc/logrotate.d/rsyslog"
sed -i -E …
```
> Delete duplicate logrotate config for `mail.log`

- scripts/common-run.sh
`postfix_disable_utf8` checks if its running on alpine and if so, disables smtputf8.
However, the check is wrong. Consider this scenario:
1. alpine container is created, smtputf8_enable is set to `no` using `-e POSTFIX_smtputf8_enable=no`
2. container is restarted. Now the `elif` branch is taken and smtputf8 is actually enabled on alpine.
3. Due to the set environment var, it is set to `no` again, so no harm done.
We actually encountered this on our system:
```
★★★★★ POSTFIX STARTING UP (alpine) ★★★★★
‣ NOTE  System accounts: postfix=100:101, opendkim=102:103. Careful when switching distros.
‣ INFO  Not setting any timezone for the container
‣ DEBUG /tmp writable.
‣ INFO  Using plain log format for rsyslog.
‣ NOTE  Emails in the logs will not be anonymized. Set ANONYMIZE_EMAILS to enable …
```
> Don't enable smtputf8 when running on alpine on container restart
